name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My First Github Actions Workflows"

        - name: List files
          run: ls

        - name: Read files
          run: cat README.md