name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Piped all the commands together
          run: |
            echo "My First Github Actions Workflows"
            ls -ltra
            cat README.md

        # - name: List files
        #   run: ls

        # - name: Read files
        #   run: cat README.md